### ISSUE TITLE
TODO 0.1

### ISSUE THREAD

**Issue by ahsis** [ahsis/MPPC#1]
TODO:
- [ ] Anonymous networks (Tor)
- [ ] Instant communication (Ricochet, Briar Project, Jitsi - as discussed on https://endchan.xyz/tech/res/10507.html#10607 )
- [ ] Meshnets
- [ ] File sharing (Retroshare, Tahoe-LAFS)
- [ ] Encryption tools (reop)
- [ ] Browsers (Links2 and uBlock for normies; don't bloat this section with shitty "muhh  addons", please use parsimony principle)
- [ ] RSS readers (newsbeuter)
- [ ] Password manager (http://www.passwordstore.org/)
- [ ] PDF security (recommend mupdf without javascript module)
- [ ] Window Managers (the openbsd version of CWM uses pledge by default)
- [ ] CryptoCoins (Dashcoin)
- [ ] Suggestion about news websites (lobste.rs, soylentnews, mailing lists, twitter RSS, etc.)
- [ ] Maybe some essential configurations (the pf firewall, for example)
